[package]
name = "mongoquery-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.150"
serde_json = "1.0.89"
thiserror = "1.0.37"

[dev-dependencies]
lazy_static = "1.4.0"
